# Generated by Django 4.2.1 on 2024-03-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterField(
            model_name='recipes',
            name='steps',
            field=models.TextField(blank=True, verbose_name='Шаги приготовления'),
        ),
    ]
