# Generated by Django 4.2.1 on 2024-03-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipes_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='cooking_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Время приготовления'),
        ),
    ]
